import AdminPage from "@/components/AdminPage";
import { ClientFlashParams } from "@/components/ClientFlashParams";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Resourcia^",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ClientFlashParams />
      {children}
    </>
  );
}
