import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import GlobalLayout from "@/components/GlobalLayout";

const DmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Resourcia^",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <GlobalLayout children={children} DmSans={DmSans} />;
}
