import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
import Footer from "@/components/footer";
// import ChatBot from "@/components/ChatBot";
// import AichatBot from "@/components/AichatBot";
import AIChatButton from "@/components/AIChatButton";
import { ClientFlashParams } from "@/components/ClientFlashParams";

const DmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Resourcia^",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={DmSans.className}>
        <ClientFlashParams />
        <Nav />
        {children}
        <Footer />
        <AIChatButton />
      </body>
    </html>
  );
}
